### PR TITLE
Use one row of blank lines on each playable example. Fixes #4.

### PR DESCRIPTION
**Pull request by metasyn**
@onewheeltom will you try this one, too?

### CODE REVIEW

**Comment by onewheeltom** [comment]
FYI, I am testing this against the website at https://metasyn.github.io/learn-orca. I am still seeing the code tags. On Safari, the one-click to paste the text is not working, and if I cut and paste. the code gets unwrapped like this 
Screen Shot 2020-10-01 at 7 25 48 PM

Still fine on Chrome except for the code tags. To clarify, when I talked about adding blank lines, I meant to change examples from
Screen Shot 2020-10-01 at 8 10 30 PM

**Comment by metasyn** [comment]
Ah yes - the changes are in this branch, not the master branch (or not on the website). Here is what I'll need you to do to verify it works or doesn't work:
```
git clone --recursive https://github.com/metasyn/learn-orca.git
cd learn-orca
make serve
```
now go to localhost:8000 in your browser. Does the issue still happen?

**Comment by onewheeltom** [comment]
Yes. The code tags are still being inserted.

Tom

**Comment by metasyn** [comment]
Ah I see. Does it corrupt the blocks for you? I'd be happy to merge this, even if it doesn't fix the problem, but alleviates it at least.

**Comment by onewheeltom** [comment]
FWIW, I'm seeing the same thing (insertion of the code tags) on my Mac (10.14.6) when I click the "auto paste" arrow next to the example. I can't test the new code locally on a chromebook anyway....I would have to use the web site or put my chromebook emulator on the same network as my Mac.

If I just cut and paste the example, there are no code tags inserted. On the Mac, all I have to do is select the example and it automatically pastes the code into the Orca window.

Tom

**Pull request closed without merging**
